/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Matrix4 */

#ifndef _Included_be_labruyere_arqanore_Matrix4
#define _Included_be_labruyere_arqanore_Matrix4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Matrix4
 * Method:    _identity
 * Signature: ()Lbe/labruyere/arqanore/Matrix4;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Matrix4__1identity
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Matrix4
 * Method:    _scale
 * Signature: (Lbe/labruyere/arqanore/Matrix4;Lbe/labruyere/arqanore/Vector3;)Lbe/labruyere/arqanore/Matrix4;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Matrix4__1scale
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Matrix4
 * Method:    _translate
 * Signature: (Lbe/labruyere/arqanore/Matrix4;Lbe/labruyere/arqanore/Vector3;)Lbe/labruyere/arqanore/Matrix4;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Matrix4__1translate
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Matrix4
 * Method:    _rotate
 * Signature: (Lbe/labruyere/arqanore/Matrix4;Lbe/labruyere/arqanore/Quaternion;)Lbe/labruyere/arqanore/Matrix4;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Matrix4__1rotate
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Matrix4
 * Method:    _perspective
 * Signature: (Lbe/labruyere/arqanore/Matrix4;FFFF)Lbe/labruyere/arqanore/Matrix4;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Matrix4__1perspective
  (JNIEnv *, jclass, jobject, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
