/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_ConcaveCollider */

#ifndef _Included_be_labruyere_arqanore_ConcaveCollider
#define _Included_be_labruyere_arqanore_ConcaveCollider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_ConcaveCollider
 * Method:    _create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_ConcaveCollider__1create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_ConcaveCollider
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_ConcaveCollider__1destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
