/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Texture */

#ifndef _Included_be_labruyere_arqanore_Texture
#define _Included_be_labruyere_arqanore_Texture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Texture
 * Method:    _create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Texture__1create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_labruyere_arqanore_Texture
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Texture__1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Texture
 * Method:    _getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Texture__1getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Texture
 * Method:    _getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Texture__1getHeight
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
