/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Scene */

#ifndef _Included_be_labruyere_arqanore_Scene
#define _Included_be_labruyere_arqanore_Scene
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Scene
 * Method:    _getCameras
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_be_labruyere_arqanore_Scene__1getCameras
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Scene
 * Method:    _getLights
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_be_labruyere_arqanore_Scene__1getLights
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Scene
 * Method:    _getActiveCamera
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Scene__1getActiveCamera
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Scene
 * Method:    _reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Scene__1reset
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Scene
 * Method:    _addCamera
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Scene__1addCamera
  (JNIEnv *, jclass, jlong);

/*
 * Class:     be_labruyere_arqanore_Scene
 * Method:    _addLight
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Scene__1addLight
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
