/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Matrix3 */

#ifndef _Included_be_labruyere_arqanore_Matrix3
#define _Included_be_labruyere_arqanore_Matrix3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Matrix3
 * Method:    _inverse
 * Signature: (Lbe/labruyere/arqanore/Matrix3;)Lbe/labruyere/arqanore/Matrix3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Matrix3__1inverse
  (JNIEnv *, jclass, jobject);

/*
 * Class:     be_labruyere_arqanore_Matrix3
 * Method:    _transpose
 * Signature: (Lbe/labruyere/arqanore/Matrix3;)Lbe/labruyere/arqanore/Matrix3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Matrix3__1transpose
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
