/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Shaders */

#ifndef _Included_be_labruyere_arqanore_Shaders
#define _Included_be_labruyere_arqanore_Shaders
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Shaders
 * Method:    _getSprite
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Shaders__1getSprite
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Shaders
 * Method:    _setSprite
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shaders__1setSprite
  (JNIEnv *, jclass, jlong);

/*
 * Class:     be_labruyere_arqanore_Shaders
 * Method:    _getPolygon
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Shaders__1getPolygon
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Shaders
 * Method:    _setPolygon
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shaders__1setPolygon
  (JNIEnv *, jclass, jlong);

/*
 * Class:     be_labruyere_arqanore_Shaders
 * Method:    _getFont
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Shaders__1getFont
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Shaders
 * Method:    _setFont
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shaders__1setFont
  (JNIEnv *, jclass, jlong);

/*
 * Class:     be_labruyere_arqanore_Shaders
 * Method:    _getModel
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Shaders__1getModel
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Shaders
 * Method:    _setModel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shaders__1setModel
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
