/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Sprite */

#ifndef _Included_be_labruyere_arqanore_Sprite
#define _Included_be_labruyere_arqanore_Sprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Sprite
 * Method:    _create
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Sprite__1create
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     be_labruyere_arqanore_Sprite
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Sprite__1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Sprite
 * Method:    _getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Sprite__1getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Sprite
 * Method:    _getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Sprite__1getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Sprite
 * Method:    _getFrameWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Sprite__1getFrameWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Sprite
 * Method:    _getFrameHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Sprite__1getFrameHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Sprite
 * Method:    _getFramesHor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Sprite__1getFramesHor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Sprite
 * Method:    _getFramesVert
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Sprite__1getFramesVert
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
