/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_MathHelper */

#ifndef _Included_be_labruyere_arqanore_MathHelper
#define _Included_be_labruyere_arqanore_MathHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_MathHelper
 * Method:    _radians
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_MathHelper__1radians
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     be_labruyere_arqanore_MathHelper
 * Method:    _degrees
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_MathHelper__1degrees
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     be_labruyere_arqanore_MathHelper
 * Method:    _lerp
 * Signature: (FFF)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_MathHelper__1lerp
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     be_labruyere_arqanore_MathHelper
 * Method:    _clamp
 * Signature: (FFF)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_MathHelper__1clamp
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
