/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Vector3 */

#ifndef _Included_be_labruyere_arqanore_Vector3
#define _Included_be_labruyere_arqanore_Vector3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _distance
 * Signature: (Lbe/labruyere/arqanore/Vector3;Lbe/labruyere/arqanore/Vector3;)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Vector3__1distance
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _angle
 * Signature: (Lbe/labruyere/arqanore/Vector3;Lbe/labruyere/arqanore/Vector3;)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Vector3__1angle
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _dot
 * Signature: (Lbe/labruyere/arqanore/Vector3;Lbe/labruyere/arqanore/Vector3;)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Vector3__1dot
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _cross
 * Signature: (Lbe/labruyere/arqanore/Vector3;Lbe/labruyere/arqanore/Vector3;)Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector3__1cross
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _normalized
 * Signature: (Lbe/labruyere/arqanore/Vector3;)Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector3__1normalized
  (JNIEnv *, jclass, jobject);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _lerp
 * Signature: (Lbe/labruyere/arqanore/Vector3;Lbe/labruyere/arqanore/Vector3;F)Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector3__1lerp
  (JNIEnv *, jclass, jobject, jobject, jfloat);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _getConstZero
 * Signature: ()Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector3__1getConstZero
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _getConstOne
 * Signature: ()Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector3__1getConstOne
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _getConstUp
 * Signature: ()Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector3__1getConstUp
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _getConstDown
 * Signature: ()Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector3__1getConstDown
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _getConstLeft
 * Signature: ()Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector3__1getConstLeft
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _getConstRight
 * Signature: ()Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector3__1getConstRight
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _getConstForward
 * Signature: ()Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector3__1getConstForward
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Vector3
 * Method:    _getConstBackward
 * Signature: ()Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector3__1getConstBackward
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
