/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Renderer */

#ifndef _Included_be_labruyere_arqanore_Renderer
#define _Included_be_labruyere_arqanore_Renderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Renderer
 * Method:    _totalParagraphRows
 * Signature: (JLjava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Renderer__1totalParagraphRows
  (JNIEnv *, jclass, jlong, jstring, jfloat);

/*
 * Class:     be_labruyere_arqanore_Renderer
 * Method:    _generateModelMatrix
 * Signature: (Lbe/labruyere/arqanore/Vector3;Lbe/labruyere/arqanore/Quaternion;Lbe/labruyere/arqanore/Vector3;)Lbe/labruyere/arqanore/Matrix4;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Renderer__1generateModelMatrix
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Renderer
 * Method:    _generateViewMatrix
 * Signature: (J)Lbe/labruyere/arqanore/Matrix4;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Renderer__1generateViewMatrix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     be_labruyere_arqanore_Renderer
 * Method:    _generateProjectionMatrix
 * Signature: (JJ)Lbe/labruyere/arqanore/Matrix4;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Renderer__1generateProjectionMatrix
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     be_labruyere_arqanore_Renderer
 * Method:    _setShader
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Renderer__1setShader
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     be_labruyere_arqanore_Renderer
 * Method:    _switchShader
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Renderer__1switchShader
  (JNIEnv *, jclass, jlong);

/*
 * Class:     be_labruyere_arqanore_Renderer
 * Method:    _renderText
 * Signature: (JJLjava/lang/String;Lbe/labruyere/arqanore/Vector2;Lbe/labruyere/arqanore/Color;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Renderer__1renderText
  (JNIEnv *, jclass, jlong, jlong, jstring, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Renderer
 * Method:    _renderParagraph
 * Signature: (JJLjava/lang/String;Lbe/labruyere/arqanore/Vector2;FLbe/labruyere/arqanore/Color;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Renderer__1renderParagraph
  (JNIEnv *, jclass, jlong, jlong, jstring, jobject, jfloat, jobject);

/*
 * Class:     be_labruyere_arqanore_Renderer
 * Method:    _renderPolygon
 * Signature: (JJJLbe/labruyere/arqanore/Vector2;Lbe/labruyere/arqanore/Vector2;Lbe/labruyere/arqanore/Vector2;Lbe/labruyere/arqanore/Vector2;FZZLbe/labruyere/arqanore/Color;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Renderer__1renderPolygon
  (JNIEnv *, jclass, jlong, jlong, jlong, jobject, jobject, jobject, jobject, jfloat, jboolean, jboolean, jobject);

/*
 * Class:     be_labruyere_arqanore_Renderer
 * Method:    _renderSprite
 * Signature: (JJLbe/labruyere/arqanore/Vector2;Lbe/labruyere/arqanore/Vector2;Lbe/labruyere/arqanore/Vector2;FIIZZLbe/labruyere/arqanore/Color;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Renderer__1renderSprite
  (JNIEnv *, jclass, jlong, jlong, jobject, jobject, jobject, jfloat, jint, jint, jboolean, jboolean, jobject);

/*
 * Class:     be_labruyere_arqanore_Renderer
 * Method:    _renderModel
 * Signature: (JJLbe/labruyere/arqanore/Vector3;Lbe/labruyere/arqanore/Quaternion;Lbe/labruyere/arqanore/Vector3;I)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Renderer__1renderModel
  (JNIEnv *, jclass, jlong, jlong, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
