/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Joystick */

#ifndef _Included_be_labruyere_arqanore_Joystick
#define _Included_be_labruyere_arqanore_Joystick
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Joystick
 * Method:    _isConnected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_Joystick__1isConnected
  (JNIEnv *, jclass, jint);

/*
 * Class:     be_labruyere_arqanore_Joystick
 * Method:    _getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_be_labruyere_arqanore_Joystick__1getName
  (JNIEnv *, jclass, jint);

/*
 * Class:     be_labruyere_arqanore_Joystick
 * Method:    _getGuid
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_be_labruyere_arqanore_Joystick__1getGuid
  (JNIEnv *, jclass, jint);

/*
 * Class:     be_labruyere_arqanore_Joystick
 * Method:    _getAxes
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_be_labruyere_arqanore_Joystick__1getAxes
  (JNIEnv *, jclass, jint);

/*
 * Class:     be_labruyere_arqanore_Joystick
 * Method:    _getButtons
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_be_labruyere_arqanore_Joystick__1getButtons
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
