/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_MeshAnimation */

#ifndef _Included_be_labruyere_arqanore_MeshAnimation
#define _Included_be_labruyere_arqanore_MeshAnimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_MeshAnimation
 * Method:    _create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_MeshAnimation__1create
  (JNIEnv *, jobject);

/*
 * Class:     be_labruyere_arqanore_MeshAnimation
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_MeshAnimation__1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_MeshAnimation
 * Method:    _getFrames
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_be_labruyere_arqanore_MeshAnimation__1getFrames
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
