/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Arqanore */

#ifndef _Included_be_labruyere_arqanore_Arqanore
#define _Included_be_labruyere_arqanore_Arqanore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Arqanore
 * Method:    _getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_be_labruyere_arqanore_Arqanore__1getVersion
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Arqanore
 * Method:    _getOpenGLVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_be_labruyere_arqanore_Arqanore__1getOpenGLVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
