/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Physics */

#ifndef _Included_be_labruyere_arqanore_Physics
#define _Included_be_labruyere_arqanore_Physics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _getGravity
 * Signature: ()Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Physics__1getGravity
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _isGravityEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_Physics__1isGravityEnabled
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _isSleepingEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_Physics__1isSleepingEnabled
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _getSleepLinearVelocity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Physics__1getSleepLinearVelocity
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _getSleepAngularVelocity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Physics__1getSleepAngularVelocity
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _getTimeBeforeSleep
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Physics__1getTimeBeforeSleep
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _setGravity
 * Signature: (Lbe/labruyere/arqanore/Vector3;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Physics__1setGravity
  (JNIEnv *, jclass, jobject);

/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _setGravityEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Physics__1setGravityEnabled
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _setSleepingEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Physics__1setSleepingEnabled
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _setSleepLinearVelocity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Physics__1setSleepLinearVelocity
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _setSleepAngularVelocity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Physics__1setSleepAngularVelocity
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     be_labruyere_arqanore_Physics
 * Method:    _setTimeBeforeSleep
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Physics__1setTimeBeforeSleep
  (JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif
