/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Color */

#ifndef _Included_be_labruyere_arqanore_Color
#define _Included_be_labruyere_arqanore_Color
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Color
 * Method:    _getConstRed
 * Signature: ()Lbe/labruyere/arqanore/Color;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Color__1getConstRed
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Color
 * Method:    _getConstGreen
 * Signature: ()Lbe/labruyere/arqanore/Color;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Color__1getConstGreen
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Color
 * Method:    _getConstBlue
 * Signature: ()Lbe/labruyere/arqanore/Color;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Color__1getConstBlue
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Color
 * Method:    _getConstCyan
 * Signature: ()Lbe/labruyere/arqanore/Color;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Color__1getConstCyan
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Color
 * Method:    _getConstYellow
 * Signature: ()Lbe/labruyere/arqanore/Color;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Color__1getConstYellow
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Color
 * Method:    _getConstPurple
 * Signature: ()Lbe/labruyere/arqanore/Color;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Color__1getConstPurple
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Color
 * Method:    _getConstWhite
 * Signature: ()Lbe/labruyere/arqanore/Color;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Color__1getConstWhite
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Color
 * Method:    _getConstBlack
 * Signature: ()Lbe/labruyere/arqanore/Color;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Color__1getConstBlack
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
