/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Vector2 */

#ifndef _Included_be_labruyere_arqanore_Vector2
#define _Included_be_labruyere_arqanore_Vector2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Vector2
 * Method:    _distance
 * Signature: (Lbe/labruyere/arqanore/Vector2;Lbe/labruyere/arqanore/Vector2;)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Vector2__1distance
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Vector2
 * Method:    _angle
 * Signature: (Lbe/labruyere/arqanore/Vector2;Lbe/labruyere/arqanore/Vector2;)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Vector2__1angle
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Vector2
 * Method:    _cross
 * Signature: (Lbe/labruyere/arqanore/Vector2;Lbe/labruyere/arqanore/Vector2;)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Vector2__1cross
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Vector2
 * Method:    _dot
 * Signature: (Lbe/labruyere/arqanore/Vector2;Lbe/labruyere/arqanore/Vector2;)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Vector2__1dot
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_Vector2
 * Method:    _normalized
 * Signature: (Lbe/labruyere/arqanore/Vector2;)Lbe/labruyere/arqanore/Vector2;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector2__1normalized
  (JNIEnv *, jclass, jobject);

/*
 * Class:     be_labruyere_arqanore_Vector2
 * Method:    _getConstZero
 * Signature: ()Lbe/labruyere/arqanore/Vector2;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector2__1getConstZero
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Vector2
 * Method:    _getConstOne
 * Signature: ()Lbe/labruyere/arqanore/Vector2;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_Vector2__1getConstOne
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
