/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_RigidBody */

#ifndef _Included_be_labruyere_arqanore_RigidBody
#define _Included_be_labruyere_arqanore_RigidBody
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_RigidBody__1create__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _create
 * Signature: (ILbe/labruyere/arqanore/Vector3;Lbe/labruyere/arqanore/Quaternion;)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_RigidBody__1create__ILbe_labruyere_arqanore_Vector3_2Lbe_labruyere_arqanore_Quaternion_2
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _getPosition
 * Signature: (J)Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_RigidBody__1getPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _getLinearVelocity
 * Signature: (J)Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_RigidBody__1getLinearVelocity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _getAngularVelocity
 * Signature: (J)Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_RigidBody__1getAngularVelocity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _getLinearLockAxis
 * Signature: (J)Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_RigidBody__1getLinearLockAxis
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _getAngularLockAxis
 * Signature: (J)Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_RigidBody__1getAngularLockAxis
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _getForce
 * Signature: (J)Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_RigidBody__1getForce
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _getTorque
 * Signature: (J)Lbe/labruyere/arqanore/Vector3;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_RigidBody__1getTorque
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _getRotation
 * Signature: (J)Lbe/labruyere/arqanore/Quaternion;
 */
JNIEXPORT jobject JNICALL Java_be_labruyere_arqanore_RigidBody__1getRotation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _getMass
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_RigidBody__1getMass
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _getLinearDamping
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_RigidBody__1getLinearDamping
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _getAngularDamping
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_RigidBody__1getAngularDamping
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _isSleeping
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_RigidBody__1isSleeping
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _isActive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_RigidBody__1isActive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _isGravityEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_RigidBody__1isGravityEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setPosition
 * Signature: (JLbe/labruyere/arqanore/Vector3;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setPosition
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setLinearVelocity
 * Signature: (JLbe/labruyere/arqanore/Vector3;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setLinearVelocity
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setAngularVelocity
 * Signature: (JLbe/labruyere/arqanore/Vector3;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setAngularVelocity
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setLinearLockAxis
 * Signature: (JLbe/labruyere/arqanore/Vector3;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setLinearLockAxis
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setAngularLockAxis
 * Signature: (JLbe/labruyere/arqanore/Vector3;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setAngularLockAxis
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setRotation
 * Signature: (JLbe/labruyere/arqanore/Quaternion;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setRotation
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setMass
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setMass
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setLinearDamping
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setLinearDamping
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setAngularDamping
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setAngularDamping
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setSleeping
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setSleeping
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setActive
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setActive
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _setGravityEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1setGravityEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _update
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1update
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _applyForce
 * Signature: (JLbe/labruyere/arqanore/Vector3;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1applyForce
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _applyTorque
 * Signature: (JLbe/labruyere/arqanore/Vector3;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1applyTorque
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _resetForce
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1resetForce
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _resetTorque
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1resetTorque
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _addCollider
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1addCollider
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     be_labruyere_arqanore_RigidBody
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_RigidBody__1dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
