/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Audio */

#ifndef _Included_be_labruyere_arqanore_Audio
#define _Included_be_labruyere_arqanore_Audio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Audio
 * Method:    _stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Audio__1stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
