/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Polygon */

#ifndef _Included_be_labruyere_arqanore_Polygon
#define _Included_be_labruyere_arqanore_Polygon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Polygon
 * Method:    _create
 * Signature: ([F[F)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Polygon__1create
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     be_labruyere_arqanore_Polygon
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Polygon__1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
