/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Shader */

#ifndef _Included_be_labruyere_arqanore_Shader
#define _Included_be_labruyere_arqanore_Shader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Shader__1create
  (JNIEnv *, jobject);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _addVertexSource
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1addVertexSource
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _addFragmentSource
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1addFragmentSource
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _compile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1compile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform1i
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform1i
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform2i
 * Signature: (JLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform2i
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform3i
 * Signature: (JLjava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform3i
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jint);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform4i
 * Signature: (JLjava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform4i
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jint, jint);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform1f
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform1f
  (JNIEnv *, jobject, jlong, jstring, jfloat);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform2f
 * Signature: (JLjava/lang/String;FF)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform2f
  (JNIEnv *, jobject, jlong, jstring, jfloat, jfloat);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform3f
 * Signature: (JLjava/lang/String;FFF)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform3f
  (JNIEnv *, jobject, jlong, jstring, jfloat, jfloat, jfloat);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform4f
 * Signature: (JLjava/lang/String;FFFF)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform4f
  (JNIEnv *, jobject, jlong, jstring, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform1d
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform1d
  (JNIEnv *, jobject, jlong, jstring, jdouble);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform2d
 * Signature: (JLjava/lang/String;DD)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform2d
  (JNIEnv *, jobject, jlong, jstring, jdouble, jdouble);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform3d
 * Signature: (JLjava/lang/String;DDD)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform3d
  (JNIEnv *, jobject, jlong, jstring, jdouble, jdouble, jdouble);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniform4d
 * Signature: (JLjava/lang/String;DDDD)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniform4d
  (JNIEnv *, jobject, jlong, jstring, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniformVec2
 * Signature: (JLjava/lang/String;Lbe/labruyere/arqanore/Vector2;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniformVec2
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniformVec3
 * Signature: (JLjava/lang/String;Lbe/labruyere/arqanore/Vector3;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniformVec3
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniformMat3
 * Signature: (JLjava/lang/String;Lbe/labruyere/arqanore/Matrix3;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniformMat3
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniformMat4
 * Signature: (JLjava/lang/String;Lbe/labruyere/arqanore/Matrix4;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniformMat4
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniformRgba
 * Signature: (JLjava/lang/String;Lbe/labruyere/arqanore/Color;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniformRgba
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setUniformRgb
 * Signature: (JLjava/lang/String;Lbe/labruyere/arqanore/Color;)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setUniformRgb
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setTexture
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setTexture
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     be_labruyere_arqanore_Shader
 * Method:    _setSprite
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Shader__1setSprite
  (JNIEnv *, jobject, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
