/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_BoxCollider */

#ifndef _Included_be_labruyere_arqanore_BoxCollider
#define _Included_be_labruyere_arqanore_BoxCollider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_BoxCollider
 * Method:    _create
 * Signature: (FFF)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_BoxCollider__1create
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     be_labruyere_arqanore_BoxCollider
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_BoxCollider__1destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
