/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Font */

#ifndef _Included_be_labruyere_arqanore_Font
#define _Included_be_labruyere_arqanore_Font
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Font
 * Method:    _create
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Font__1create
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     be_labruyere_arqanore_Font
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Font__1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Font
 * Method:    _measure
 * Signature: (JLjava/lang/String;F)F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Font__1measure
  (JNIEnv *, jobject, jlong, jstring, jfloat);

#ifdef __cplusplus
}
#endif
#endif
