/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Model */

#ifndef _Included_be_labruyere_arqanore_Model
#define _Included_be_labruyere_arqanore_Model
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Model
 * Method:    _create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Model__1create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_labruyere_arqanore_Model
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Model__1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Model
 * Method:    _getMeshes
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_be_labruyere_arqanore_Model__1getMeshes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Model
 * Method:    _totalVertices
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Model__1totalVertices
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Model
 * Method:    _totalTexcoords
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Model__1totalTexcoords
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Model
 * Method:    _totalNormals
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Model__1totalNormals
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Model
 * Method:    _totalFrames
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Model__1totalFrames
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Model
 * Method:    _calculateNormals
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Model__1calculateNormals
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
