/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Mesh */

#ifndef _Included_be_labruyere_arqanore_Mesh
#define _Included_be_labruyere_arqanore_Mesh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Mesh
 * Method:    _create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Mesh__1create
  (JNIEnv *, jobject);

/*
 * Class:     be_labruyere_arqanore_Mesh
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Mesh__1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Mesh
 * Method:    _getVertices
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_be_labruyere_arqanore_Mesh__1getVertices
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Mesh
 * Method:    _getNormals
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_be_labruyere_arqanore_Mesh__1getNormals
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Mesh
 * Method:    _getTexCoords
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_be_labruyere_arqanore_Mesh__1getTexCoords
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Mesh
 * Method:    _getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_be_labruyere_arqanore_Mesh__1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Mesh
 * Method:    _getAnimation
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Mesh__1getAnimation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_labruyere_arqanore_Mesh
 * Method:    _getMaterial
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_Mesh__1getMaterial
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
