/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_SphereCollider */

#ifndef _Included_be_labruyere_arqanore_SphereCollider
#define _Included_be_labruyere_arqanore_SphereCollider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_SphereCollider
 * Method:    _create
 * Signature: (F)J
 */
JNIEXPORT jlong JNICALL Java_be_labruyere_arqanore_SphereCollider__1create
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     be_labruyere_arqanore_SphereCollider
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_SphereCollider__1destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
