/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Mouse */

#ifndef _Included_be_labruyere_arqanore_Mouse
#define _Included_be_labruyere_arqanore_Mouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Mouse__1getX
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Mouse__1getY
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _getMoveX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Mouse__1getMoveX
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _getMoveY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_be_labruyere_arqanore_Mouse__1getMoveY
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _getScrollX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Mouse__1getScrollX
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _getScrollY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_be_labruyere_arqanore_Mouse__1getScrollY
  (JNIEnv *, jclass);

/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _buttonDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_Mouse__1buttonDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _buttonUp
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_Mouse__1buttonUp
  (JNIEnv *, jclass, jint);

/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _buttonPressed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_Mouse__1buttonPressed
  (JNIEnv *, jclass, jint);

/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _hide
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Mouse__1hide
  (JNIEnv *, jclass, jlong);

/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _disable
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Mouse__1disable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     be_labruyere_arqanore_Mouse
 * Method:    _show
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_be_labruyere_arqanore_Mouse__1show
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
