/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_labruyere_arqanore_Keyboard */

#ifndef _Included_be_labruyere_arqanore_Keyboard
#define _Included_be_labruyere_arqanore_Keyboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_labruyere_arqanore_Keyboard
 * Method:    _keyUp
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_Keyboard__1keyUp
  (JNIEnv *, jclass, jint);

/*
 * Class:     be_labruyere_arqanore_Keyboard
 * Method:    _keyDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_Keyboard__1keyDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     be_labruyere_arqanore_Keyboard
 * Method:    _keyPressed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_be_labruyere_arqanore_Keyboard__1keyPressed
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
